name: 构建二进制可执行文件

on:
  workflow_dispatch: 
  pull_request: 
    paths:
      - "language.cs"
      # 只在源代码被更新时运行
  push:
    paths:
      - "language.cs"
jobs:

  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            artifact: language
          - runner: ubuntu-26.04-arm
            artifact: language_arm
    steps:
      - uses: actions/checkout@v7

      - name: 编译
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/src \
            -w /src \
            alpine:latest /bin/sh -c '
              apk update
              apk add build-base dotnet10-sdk clang
              dotnet publish language.cs /t:Rebuild --disable-build-servers --force '          
      - name: 重命名
        if: ${{ matrix.runner == 'ubuntu-26.04-arm' }}
        run: sudo mv artifacts/language/language artifacts/language/language_arm
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: artifacts/language/${{ matrix.artifact }}